function exp2csv ( e )

% This function writes three files, 'main(Run#).csv', 'per(Run#).csv', and
% run(Run#).csv'. Which each contain the information held by the 'exp.mat'
% file generated by genExp.m. The .csv file is in LONG form which can then
% be read and manipulated by R later.
% Caution:
%   This design is straightforward, but re-organizes the data according to
%   trial numbers. If there is an error in this function, it will propagate
%   throughout your analysis and be very difficult to detect. If you modify
%   this, run some case tests before comitting your modifications.

main = e{1};
per = e{2};
run = e{3};

% for saving files
runNum = run.runVars.runNum;

saveLoc = fullfile('~/proj/att_awe/analysis/',mglGetSID,'csv');

if ~isdir(saveLoc)
    mkdir(saveLoc);
end
mainFile = fullfile(saveLoc,sprintf('main%02.f.csv',runNum));
perFile = fullfile(saveLoc,sprintf('per%02.f.csv',runNum));
runFile = fullfile(saveLoc,sprintf('run%02.f.csv',runNum));

%% Write Main

% First re-organize into a matrix, tracking the headers
mainHeader = {'trial','RT','correct','response' ...
    'interval','tPos','tGen','tCon1','tCon2','tNoi1','tNoi2','dPed','img'};
    % peripheral items

% For each item in the header (re-named) what is the corresponding data?
corrData = {'blockTrialNum','reactionTime','correct','response'};
% These come AFTER all the corrData items. They are pulled from
% 'main.randVars'
randData = {'interval','targetLoc','gender','tCon1','tCon2','tNoise1','tNoise2','deltaPed','tImage'};

if length(randData)+length(corrData) ~= length(mainHeader)
    error('Lengths are incorrect! Check your variables');
end

mainData = [];

% mainData(:,1) % COLUMN 1
for i = 1:length(corrData)
    mainData(:,end+1) = main.(corrData{i});
end

for j = 1:length(randData)
    mainData(:,end+1) = main.randVars.(randData{j});
end

% Now write to mainFile
csvwriteh(mainFile,mainData,mainHeader);

%% Write Peripheral

% First re-organize into a matrix, tracking the headers
perHeader = {'correct','RT','response','sLength',...
    'mainTrial','position','respond','SOA','tGen','tImg'};
% For each item in the header (re-named) what is the corresponding data?
corrData = {'correct','reactionTime','response','stimPresLength'};
% These come AFTER all the corrData items. They are pulled from
% 'main.randVars'
randData = {'mainTrialNum','position','respond','SOA','tGen','tImage'};

if length(randData)+length(corrData) ~= length(perHeader)
    error('Lengths are incorrect! Check your variables');
end

perData = [];

% mainData(:,1) % COLUMN 1
for i = 1:length(corrData)
    perData(:,end+1) = per.(corrData{i});
end

for j = 1:length(randData)
    try
        perData(:,end+1) = per.randVars.(randData{j});
    catch
        perData(:,end+1) = NaN;
    end
end

% Now write to perFile
csvwriteh(perFile,perData,perHeader);

%% Write run

runHeader = {'dual','blockType'};
runData = [run.runVars.dual run.runVars.blocks(end)];

csvwriteh(runFile,runData,runHeader);

%% Write Staircases

% Don't need this at the moment... Although maybe I want to move the
% staircases into R at some point?

end
