
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(effects)
library(lme4)
```

```{r}
d = read.csv('~/proj/att_awe/analysis/data/s0300_voxels.csv')
```

```{r}
data = d %>%
  mutate(task=factor(task,levels=c(1,2),labels=c("Attend Coh","Attend Con")),
         roi=factor(roi,levels=1:9,
                    labels=c('V3a','V3b','V1','V2','V3','MT','LO1','LO2','V4'))) %>%
  filter(amplitude < 10, amplitude > -10)
```


```{r}
rois = levels(data$roi)

lmdata = data.frame(ec=numeric(0),em=numeric(0),attending=numeric(0),voxel=numeric(0),roi=numeric(0))

for (rii in 1:length(rois)) {
  ri = rois[rii]
  roidata = data %>%
    filter(roi==ri)
  voxels  = unique(roidata$voxel)
  for (vi in 1:length(voxels)) {
    vox = voxels[vi]
    rsd = roidata %>%
      filter(voxel==vox)
    rs = lm(amplitude ~ task*(con + coh),data=rsd)
    eff_con_att_con = rs$coefficients[3]
    eff_con_att_coh = rs$coefficients[3]+rs$coefficients[5]
    eff_coh_att_con = rs$coefficients[4]
    eff_coh_att_coh = rs$coefficients[4]+rs$coefficients[6]
    
    lmdata[nrow(lmdata)+1,] = c(ec=eff_con_att_con,em=eff_coh_att_con,attending=0,voxel=vox,roi = rii)
    lmdata[nrow(lmdata)+1,] = c(ec=eff_con_att_coh,em=eff_coh_att_coh,attending=1,voxel=vox, roi = rii)
  }
}
```

```{r}

lmdata = lmdata %>%
  mutate(attending=factor(attending,levels=c(0,1),labels=c("Contrast","Coherence")),
         voxel=factor(voxel),
         roi = factor(roi,levels=1:9,labels=rois))

```


```{r}
g = ggplot(data=lmdata, aes(ec,em,color=attending)) +
  geom_point(size=0.5) +
  geom_smooth(method="lm") +
  facet_grid(.~roi, scales="fixed") +
  xlab('Effect Across Contrast 0->1 (beta)') +
  ylab('Effect Across Coherence 0->1 (beta)') +
  coord_fixed() +
  theme_bw()
g
```


Generate indiviual ROI plots with marginals:

```{r}
localdata = lmdata %>%
  filter(roi=='V1')
pMain <- localdata %>%
  ggplot(data=., aes(ec,em,color=attending)) +
  geom_point() +
  geom_smooth(method="lm") +
  facet_grid(.~roi, scales="fixed") +
  xlab('Effect Across Contrast 0->1 (beta)') +
  ylab('Effect Across Coherence 0->1 (beta)') +
  theme_bw()
pTop <- ggplot(localdata, aes(x = ec, fill = attending)) +
        geom_density(alpha=0.5) +
        theme_bw()
pRight <- ggplot(localdata, aes(x = em, fill = attending)) +
        geom_density(alpha=0.5) +
        coord_flip() +
        theme_bw()
pEmpty <- ggplot(localdata, aes(ec,em)) +
          geom_blank() +
          theme(axis.text = element_blank(),
                axis.title = element_blank(),
                line = element_blank(),
                panel.background = element_blank())

grid.arrange(pTop, pEmpty, pMain, pRight,
             ncol = 2, nrow = 2, widths = c(3, 1), heights = c(1, 3))

```



