---
title: "cohCon_analyze"
output: html_document
---

```{r}
library(ggplot2)    
library(dplyr)
library(tidyr)
library(lme4)
library(effects)
library(MASS)
```

```{r}
getSubjThresholdPlot = function(type,snum) {
library(dplyr)
subj = sprintf('s%03.0f',snum)
if (type=='behav') {
  anFolder = sprintf('/Users/dan/data/cohcon/%s/behav/analysis/',subj)
  csvFolder = paste(anFolder,'csv/',sep="")
} else {
  anFolder = sprintf('/Users/dan/data/cohcon/scan2/%s/behav/analysis/',subj)
  csvFolder = paste(anFolder,'csv/',sep="")
}
figFolder = paste('/Users/dan/proj/att_awe/analysis/','figures/',type,sep="")
mainTh = read.csv(sprintf('%smainThresholds.csv',csvFolder))
catTh = read.csv(sprintf('%scatThresholds.csv',csvFolder))
nocatTh = read.csv(sprintf('%snocatThresholds.csv',csvFolder))
mainTh = cbind(mainTh,catch=0)
catTh = cbind(catTh,catch=1)
nocatTh = cbind(nocatTh,catch=-1)
run = read.csv(sprintf('%srun04.csv',csvFolder))

# Setup variables
all = rbind(mainTh,catTh,nocatTh) %>%
  mutate(task=factor(task,levels=c(1,2),labels=c('Coherence','Contrast')),catch=factor(catch,levels=c(-1,0,1),labels=c('Nocatch','Cued','Miscued')),threshold=threshold*100)
all_ = all %>%
  group_by(task,catch) %>%
  summarise(sd=sd(threshold),n=n(),threshold=mean(threshold)) %>%
  mutate(se = sd/sqrt(n)) %>%
  mutate(ci = se*1.96)

# Calculate pooled variance
if (all(all_$n>2)) {
ES = all_ %>% ungroup() %>%
  filter(catch!='Nocatch') %>%
  group_by(task) %>%
  mutate(pooled = sqrt(sum(sd^2*(n-1))/sum(n-1))) %>%
  summarise(t=mean(threshold),effect = diff(threshold,lag=1)/mean(pooled))
}

 # Individual plot,
fname=sprintf('%s/%s_th_task_catch.pdf',figFolder,subj)
g = ggplot() +
  geom_errorbar(data=all_,aes(task,threshold,fill=catch,ymin=threshold-ci,ymax=threshold+ci),position=position_dodge(width=.75),width=0) +
  geom_point(data=all,aes(task,threshold,color=catch,group=catch),position=position_dodge(width=.75),size=4) +
  geom_point(data=all_,aes(task,threshold,color=catch),position=position_dodge(width=.75),size=24,shape='-') +
  theme_bw() +
  scale_fill_brewer() +  
  scale_color_brewer() +
  theme(text = element_text(size=20)) +
  xlab('Pedestal Value (%)') +
  ylab('Discrimination Threshold (%)') #+
#   geom_text(data=ES,aes(x=task,y=t+.05,label=round(effect,2)))
ggsave(filename=fname,plot=g)

# LM
contrasts(all$catch) = cbind(c(-1,-1,2),c(-1,0,1))
rs = lm(data=all,threshold ~ task*catch)
# plot(allEffects(rs))

all = cbind(all,subj=snum)

return(all)
}
```

```{r}
getSubjFits = function(type,snum) {
subj = sprintf('s%03.0f',snum)
if (type=='behav') {
  anFolder = sprintf('/Users/dan/data/cohcon/%s/behav/analysis/',subj)
  csvFolder = paste(anFolder,'csv/',sep="")
} else {
  anFolder = sprintf('/Users/dan/data/cohcon/scan2/%s/behav/analysis/',subj)
  csvFolder = paste(anFolder,'csv/',sep="")
}
figFolder = paste('/Users/dan/proj/att_awe/analysis/','figures/',type,sep="")
fits = read.csv(sprintf('%smodelFits.csv',csvFolder))
fits = fits %>%
  mutate(subj=snum,task=factor(task,levels=c(1,2),labels=c('Coherence','Contrast')),catch=factor(catch,levels=c(-1,0,1),labels=c('Nocatch','Cued','Miscued')))
return(fits)
}
```

```{r}
subjs = c(300,25,21,302)

allT = data.frame()
allF = data.frame()
for (snum in subjs) {
  all = getSubjThresholdPlot('behav',snum)
  fit = getSubjFits('behav',snum)
  allF = rbind(allF,fit)
  allT = rbind(allT,all)
}
```

Now let's normalize the weibull fits and see if they vary consistently across subjects.
```{r}
norms = allF %>%
  group_by(task,subj,catch) %>%
  filter(catch=='Nocatch') %>%
  summarise(normT = mean(T)) %>%
  select(-catch)
allF = left_join(allF,norms)
```

Okay that's done. Now we can mutate with the normalized Ts

```{r}
allF_ = allF %>%
  mutate(T = T / normT) %>%
  select(-normT) %>%
  group_by(task,catch,subj) %>%
  summarise(T=mean(T),beta=mean(beta))

allF_mu = allF_ %>%
  group_by(task,catch) %>%
  summarise(ciT=sd(T)/sqrt(n())*1.96,T=mean(T),cibeta=sd(beta)/sqrt(n())*1.96,beta=mean(beta))
```


```{r}
x = seq(0,4,.01)

weib = data.frame(x=c())

for (i in seq(1,nrow(allF_))) {
  t = allF_[i,]$T
  b = allF_[i,]$beta
  for (xval in x) {
    weib = rbind(weib,c(xval,1-(exp(-(xval/t)^b)),allF_[i,]$subj,allF_[i,]$task,allF_[i,]$catch))
  }
}

names(weib) = c('x','y','subj','task','catch')
weib = weib %>%
  mutate(task=factor(task,levels=c(1,2),labels=c('Coherence','Contrast')),catch=factor(catch,levels=c(1,2,3),labels=c('Control','Task Cued','Task Miscued')))
```

```{r}
weib2 = data.frame(x=c())
for (i in seq(1,nrow(allF_mu))) {
  t = allF_mu[i,]$T
  b = allF_mu[i,]$beta
  for (xval in x) {
    weib2 = rbind(weib2,c(xval,1-(exp(-(xval/t)^b)),allF_mu[i,]$task,allF_mu[i,]$catch))
  }
}
names(weib2) = c('x','y','task','catch')
weib2 = weib2 %>%
  mutate(task=factor(task,levels=c(1,2),labels=c('Coherence','Contrast')),catch=factor(catch,levels=c(1,2,3),labels=c('Control','Task Cued','Task Miscued')))
```

```{r}
ggplot() +
  geom_line(data=weib2,aes(x,y,color=catch),size=3) +
  geom_line(data=weib,aes(x,y,color=catch),size=1,alpha=.2) +
  scale_color_brewer(palette='Dark2') +
  facet_grid(.~task) +
  theme_bw() +
  ggtitle('Discrimination Functions--Parameter Averages Across Subjects (n=4)') +
  xlab('Threshold Normalized to Nocatch Runs (au)') +
  ylab('Performance (% Correct)') +
  theme(text = element_text(size=20))
```


```{r}
ggplot(weib) +
  geom_line(aes(x,y_Coherence_Nocatch),color='darkorange4',size=2) +
  geom_line(aes(x,y_Coherence_Cued),color='darkorange3',size=2) +
  geom_line(aes(x,y_Coherence_Miscued),color='darkorange1',size=2) +
  geom_line(aes(x,y_Contrast_Nocatch),color='turquoise4',size=2) +
  geom_line(aes(x,y_Contrast_Cued),color='turquoise3',size=2) +
  geom_line(aes(x,y_Contrast_Miscued),color='turquoise1',size=2) +
  theme_bw()
```



```{r}
contrasts(allT$catch) = cbind(c(-1,-1,2),c(-1,0,1))
rs = lmer(data=allT,threshold ~ task*catch + (1|subj))
rs2 = lmer(data=allT,threshold~task*catch + (1+task|subj))
# rs3 = lmer(data=allT,threshold~task*catch + (task+catch|subj))
# rs4 = lmer(data=allT,threshold~task*catch + (task*catch|subj))
anova(rs,rs2,rs3,rs4)
plot(allEffects(rs2))
```

Plot the across subject data with curve estiamtes
```{r}
ggplot(data=allT,aes(catch,threshold,color=factor(subj),)) +
  geom_point(size=4) +
  facet_grid(.~task) +
  scale_color_brewer(palette='Dark2') +
  scale_fill_brewer(palette='Dark2') +
  theme_bw() +
  geom_smooth(aes(group=factor(subj),fill=factor(subj)),method="loess")
```

Now calculate the effect size, and average effect size across subjects
```{r}
ES = allT %>%
  group_by(task,subj,catch) %>%
  summarise(sd=sd(threshold),n=n(),threshold=mean(threshold)) %>%
  filter(n>1,subj==300,catch!='Nocatch') %>%
  mutate(pooled=sqrt(sum(sd^2*(n-1)/sum(n-1)))) %>%
  summarise(effect = diff(threshold,lag=1)/mean(pooled),t=mean(threshold)) %>%
  summarise(ci=sd(effect)/sqrt(n())*1.96,average_eff = mean(effect))
```


```{r}
# 
figFolder = '/Users/dan/proj/att_awe/analysis/figures/behav/'
# pdf(file=sprintf('%s/thresholdPlot_all.pdf',figFolder))
allT %>%
  mutate(pedVal=pedVal*100,mu=mu*100,ci=ci*100) %>%
  filter(subj==300) %>%
  ggplot(data=.) +
    geom_point(aes(pedVal,mu,color=task,linetype=catch),size=4) +
    geom_line(aes(pedVal,mu,color=task,linetype=catch),size=.5) +
    geom_errorbar(aes(pedVal,mu,color=task,linetype=catch,ymin=mu-ci,ymax=mu+ci),size=.5,width=0) +
    theme_bw() +
    ylab('80% Threshold') +
    xlab('Stimulus Contrast (%)') +
    scale_y_log10(breaks = trans_breaks("log10", function(x) round(10^x,0))) +
    scale_x_log10(breaks = trans_breaks("log10", function(x) round(10^x,0))) +
    annotation_logticks(scaled=T) +
    theme(text = element_text(size=15)) +
    scale_color_brewer(palette='Paired')
# dev.off()
```

```{r}
# Reaction time analysis
filesToLoad = c(1,2,3,4,7,8,9)
subj = 's300'
type = 'behav'
if (type=='behav') {
  anFolder = sprintf('/Users/dan/data/cohcon/%s/analysis/',subj)
  csvFolder = paste(anFolder,'csv/',sep="")
} else {
  anFolder = sprintf('/Users/dan/data/cohcon/scan2/%s/analysis/',subj)
  csvFolder = paste(anFolder,'csv/',sep="")
}
for (fi in filesToLoad) {
  # Dealing with run # fi
  main = read.csv(sprintf('%s/main%02.f.csv',csvFolder,fi))  
  # Switch to determine what kind of analysis we do
  main = main %>% 
    mutate(rTrial=(run-1)*100+trialNum)
  
  if (fi==1) {
    mdata = main
  } else {
    mdata = rbind(mdata,main)
  }
}

cdata = mdata %>%
  filter(isCatch==1)

mdata = mdata %>%
  mutate(congruent=factor(cohSide==conSide),correctF=factor(correct,levels=c(0,1),labels=c('Incorrect','Correct')),conSide=factor(conSide,levels=c(1,2),labels=c('Left','Right')),cohSide=factor(cohSide,levels=c(1,2),labels=c('Left','Right')),taskF=factor(task,levels=c(1,2),labels=c('Coherence','Contrast')),conPedestal=factor(conPedestal),cohPedestal=factor(cohPedestal),isCatch=factor(isCatch,levels=c(0,1),labels=c('Cued','Miscued')))

rs = lm(data=mdata,RT ~ correctF + taskF*cohDelta + taskF*conDelta + isCatch*congruent + taskF*conSide + taskF*cohSide + rTrial)
rs = lm(data=mdata,RT ~ correctF*isCatch*congruent*taskF)
plot(allEffects(rs))

ggplot(mdata,aes(taskF,RT,linetype=congruent,color=correctF)) +
  geom_point(size=3) +
  geom_smooth(method="lm",formula=y~x^2) +
  scale_color_brewer(palette='Dark2') +
  facet_grid(.~isCatch)
```
