---
title: "discriminationPerformance"
author: Dan Birman
date: "January 22, 2015"
output: html_document
---

Loading some important stuff

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(lme4)
```

Loading the data files

```{r}
main = read.csv('C:\\Users\\Dan\\proj\\att_awe\\analysis\\cue_noisecon\\s300\\csv\\mainThresholds.csv')
per = read.csv('C:\\Users\\Dan\\proj\\att_awe\\analysis\\cue_noisecon\\s300\\csv\\perThresholds.csv')
```

Cleaning up the data files

```{r}
noise = c(0.0758581800212435,         0.148047198031689,         0.268941421369995,         0.437823499114202,         0.622459331201855)
noisePed = noise[2:4]
contrast = c(.1, .15, .25, .4, .6)
contrastPed = contrast[2:4]
```

```{r cleanup}
main2 = main %>%
  mutate(taskf = factor(task,levels=c(1,2),labels=c('Noise','Contrast'))) %>% 
  mutate(cuesf = factor(cues,levels=c(1,2),labels=c('One','Four')))%>%
  mutate(pedf = factor(pedestal,levels=c(1,2,3),labels=c('1','2','3'))) %>%
  filter(threshold>0,threshold<.55) %>%
  mutate(dualf = factor(dual,levels=c(1,2),labels=c('Single','Dual')))
mainmean = main2 %>%
  group_by(taskf,cuesf,pedf,dualf) %>%
  summarise(mu=mean(threshold),sd=sd(threshold))
per2 = per %>% 
  mutate(taskf = factor(task,levels=c(1,2,3),labels=c('Single','Dual:Noise','Dual:Contrast'))) %>%
  filter(threshold>0,threshold<.25)
permean = per2 %>% group_by(taskf) %>% summarise(mu=mean(threshold),sd=sd(threshold))
```

Now let's add the pedestal values for noise and contrast into the data.frame, this is a bit of a pain and unfortunately I don't know a better solution.
```{r}
single = mainmean %>% filter(cuesf=='One',dualf=='Single') %>% group_by(taskf,pedf) %>% summarise(single = mean(mu))
pedFrame = data.frame(taskf=c('Noise','Noise','Noise',
                   'Contrast','Contrast','Contrast'),
           pedestal=c(1,2,3,
                      1,2,3),
           single=c(single$single[1:3],
                          single$single[4:6]))
main3 = main2 %>% merge(pedFrame)
```

Now let's normalize all of our data by the single task values.

```{r}
sem = function(values) {
  return(1.96*sd(values) / sqrt(length(values)))
}
perNorm = per2 %>%
  mutate(single = permean[1,2]$mu) %>%
  mutate(nThresh = 1/(threshold / single))
mainNorm = main3 %>%
  mutate(nThresh = 1/(threshold / single))
```

Fixing data by averaging across pedestals
```{r}
mainROC = mainNorm %>%
  filter(cuesf=='One') %>%
  group_by(taskf,dualf) %>%
  summarise(mu=mean(nThresh),sd=sem(nThresh))
perROC = perNorm %>%
  group_by(taskf) %>%
  summarise(mu=mean(nThresh),sd=sem(nThresh))
mainROC$y = c(0,perROC$mu[2],0,perROC$mu[3])
mainROC$ysd = c(0,perROC$sd[2],0,perROC$sd[3])
```

Data is in ROC, now we need to plot
```{r}
 # ROC Plotp
ggplot(mainROC) +
  geom_point(aes(mu,y,color=taskf,shape=dualf),size=4) +
  geom_point(aes(0,perROC$mu[1]),color='black',size=4) +
  geom_errorbar(aes(x=mu,y=y,ymin=y-ysd,ymax=y+ysd,color=taskf,shape=dualf),width=.05) +
  geom_errorbar(aes(x=0,y=perROC$mu[1],ymin=perROC$mu[1]-perROC$sd[1],ymax=perROC$mu[1]+perROC$sd[1]),width=.1) +
  geom_errorbarh(aes(x=mu,y=y,xmin=mu-sd,xmax=mu+sd,color=taskf,shape=dualf),width=.05) +
  geom_vline(xintercept=mainROC$mu[1],color='#F8766D',linetype='dashed',size=1) +
  geom_vline(xintercept=mainROC$mu[3],color='#00BFC4',linetype='dashed',size=1) +
  geom_hline(yintercept=perROC$mu[1],color='black',linetype='dashed',size=1) +
  xlab('Performance on Main Task') +
  ylab('Performance on Gender Task') +
  theme_bw() +
  scale_x_continuous(breaks=c(0)) +
  scale_y_continuous(breaks=c(0)) +
  theme(text=element_text(size=25)) +
  labs(color="Task",shape="Dual")
```

