function exp2csv ( exp )

% This function writes three files, 'main(Run#).csv', 'per(Run#).csv', and
% run(Run#).csv'. Which each contain the information held by the 'exp.mat'
% file generated by genExp.m. The .csv file is in LONG form which can then
% be read and manipulated by R later.
% Caution:
%   This design is straightforward, but re-organizes the data according to
%   trial numbers. If there is an error in this function, it will propagate
%   throughout your analysis and be very difficult to detect. If you modify
%   this, run some case tests before comitting your modifications.

main = exp{1};
per = exp{2};
run = exp{3};

% for saving files
runNum = run.runVars.runNum;

saveLoc = fullfile('~/proj/att_awe/analysis/',mglGetSID,'csv');

if ~isdir(saveLoc)
    mkdir(saveLoc);
end
mainFile = fullfile(saveLoc,sprintf('main%02.f.csv',runNum));
perFile = fullfile(saveLoc,sprintf('per%2.f.csv',runNum));
runFile = fullfile(saveLoc,sprintf('run%2.f.csv',runNum));

%% Write Main

% First re-organize into a matrix, tracking the headers
mainHeader = {'trial'};
% For each item in the header (re-named) what is the corresponding data?
corrData = {'blockTrialNum'};
% These come AFTER all the corrData items. They are pulled from
% 'main.randVars'
randData = {};

if length(randData)+length(corrData) ~= length(mainHeader)
    error('Lengths are incorrect! Check your variables');
end

mainData = [];

% mainData(:,1) % COLUMN 1
for i = 1:length(corrData)
    mainData(:,end+1) = main.(corrData{i});
end

for j = 1:length(randData)
    mainData(:,end+1) = main.(randData{j});
end

% Now write to mainFile
csvwriteh(mainFile,mainData,mainHeader);

%% Write PEripheral

% First re-organize into a matrix, tracking the headers
perHeader = {};
% For each item in the header (re-named) what is the corresponding data?
corrData = {'blockTrialNum'};
% These come AFTER all the corrData items. They are pulled from
% 'main.randVars'
randData = {'mainTrialNum'};

if length(randData)+length(corrData) ~= length(perHeader)
    error('Lengths are incorrect! Check your variables');
end

mainData = [];

% mainData(:,1) % COLUMN 1
for i = 1:length(corrData)
    mainData(:,end+1) = per.(corrData{i});
end

for j = 1:length(randData)
    mainData(:,end+1) = per.(randData{j});
end

% Now write to mainFile
csvwriteh(mainFile,mainData,perHeader);
%% Write Run

end
