---
title: "reactionTime"
author: "Dan Birman"
date: "January 22, 2015"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(lme4)
```

```{r}
cleanup <- function(data) {
  data %>% 
    filter(!is.nan(response)) %>%
    mutate(RT = RT*1000,correct=factor(correct,levels=c(0,1),labels=c("inc","cor"))) %>%
    mutate(taskf = factor(task,levels=c(1,2),labels=c('noise','contrast'))) %>%
    mutate(dualf = factor(dual,levels=c(0,1),labels=c('single','dual'))) %>%
    mutate(index = 1:nrow(.))
}
```


Let's start loading our data

```{r}

filesToLoad = 1:52

for (fi in filesToLoad) {
  # Dealing with run # fi
  main = read.csv(sprintf('../analysis/s300/csv/main%02.f.csv',fi))
  per = read.csv(sprintf('../analysis/s300/csv/per%02.f.csv',fi))
  run = read.csv(sprintf('../analysis/s300/csv/run%02.f.csv',fi))
  
  # Switch to determine what kind of analysis we do
  main = main %>% 
    mutate(dual=run$dual) %>%
    mutate(task=run$blockType)
  
  per = per %>% 
    mutate(dual=run$dual) %>%
    mutate(task=run$blockType)
  
  if (fi==1) {
    mdata = main
    pdata = per
  } else {
    mdata = rbind(mdata,main)
    pdata = rbind(pdata,per)
  }
}

# Do a final cleanup
mdata = cleanup(mdata)
pdata = cleanup(pdata)
  
```

Now let's start the analysis, using `mdata` and `pdata`. 

Is there a difference in response speed for noise vs. contrast, single vs. dual
```{r}
mdata %>%
  ggplot(aes(ped,RT,color=correct)) +
  geom_point() +
  geom_smooth(method="lm") +
  facet_grid(taskf~dualf) +
  theme_bw()
mdata %>%
  lm(data=.,RT ~ taskf + dualf + dPed + correct + index) %>%
  summary
```

